version: "3.3"

services:
  gcc: 
    container_name: gcc-container-dev
    image: gcc:11.1
    command: ["bash"]
    stdin_open: true
    working_dir: "/usr/src"
    volumes: 
      - ./src/moderncpp:/usr/src/moderncpp:cached
      - /home/ccq/.vscode-server:/root/.vscode-server:cached
    networks: 
      - gcc-network

networks:
  gcc-network: 